# automations for notification of motion detector
 
- id: '1591029884000'
  alias: 'Flush: Motion Detected'
  description: ''
  trigger:
  - device_id: 8ca8f1a8fce04d4ab0d3199bdd7e4fde
    domain: binary_sensor
    entity_id: binary_sensor.pir_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
    platform: device
    type: motion
  condition: []
  action:
  - data:
      message: Motion Detected
    service: notify.mobile_app_skeeter_s_pixel
