#/config/esphome/flush.yaml

esphome:
  name: flush
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "****"
  password: "*****"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
            
ota:

#LED
output:
  - platform: gpio
    pin: D1
    id: led
#Servo    
  - platform: esp8266_pwm
    id: pwm_output
    pin: D8
    frequency: 50 Hz

servo:
  - id: my_servo
    output: pwm_output
    idle_level: 3.0%
    min_level: 3.0%
    max_level: 12.0%
    restore: false

binary_sensor:
  - platform: gpio
    pin: D7
    name: "PIR Sensor"
    device_class: motion
    on_press:
      then:
        - output.turn_on: led
    on_release:
      then:
        - output.turn_off: led

switch:
  - platform: template
    icon: "mdi:toilet"
    name: "Flush Toilet"
    turn_on_action:
    - output.set_level:
        id: pwm_output
        level: 10%
    - delay: 1000ms
    - output.set_level:
        id: pwm_output
        level: 3.0%
