#/config/esphome/flush.yaml

esphome:
  name: flush
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "****"
  password: "*****"

captive_portal:

debug:

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:

ota:

output:
# LED
  - platform: gpio
    pin: D1
    id: led
    
# Servo Output
  - platform: esp8266_pwm
    id: pwm_output
    pin: D8
    frequency: 50 Hz

# Servo Params
servo:
  - id: my_servo
    output: pwm_output
    idle_level: 3.0%
    min_level: 3.0%
    max_level: 12.0%
    restore: false

# Motion Sensor
binary_sensor:
  - platform: gpio
    pin: D7
    name: "PIR Sensor"
    device_class: motion
    id: pir_motion
    on_press:
      - output.turn_on: led
      - logger.log: "LED is on."
# Night Light
  - platform: template
    id: led_timer
    lambda: 'return id(pir_motion).state;'
    filters:
      - delayed_off: 30s
    on_release:
      - output.turn_off: led
      - logger.log: "LED is off."

# Flush Buttons
switch:
  - platform: template
    icon: "mdi:toilet"
    name: "Flush Toilet"
    turn_on_action:
    - output.set_level:
        id: pwm_output
        level: 12%
    - delay: 1000ms
    - output.set_level:
        id: pwm_output
        level: 3.0%

  - platform: restart
    name: "Toilet Flush MCU Reset"
