#/config/esphome/flush.yaml

esphome:
  name: flush
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: my_servo
            level: !lambda 'return level / 100.0;'
            
ota:

servo:
  - id: my_servo
    output: pwm_output

binary_sensor:
  - platform: gpio
    pin: D6
    name: "PIR Sensor"
    device_class: motion
    on_press:
      then:
        - output.turn_on: led
    on_release:
      then:
        - output.turn_off: led

output:
  - platform: gpio
    pin: D1
    id: led
    
  - platform: esp8266_pwm
    id: pwm_output
    pin: D2
    frequency: 50 Hz
